/**
 * permissions.ts
 * ==============
 * クライアントサイドでの細粒度RBAC判定ヘルパー。
 * backend/src/common/guards/permissions.guard.ts の ROLE_PERMISSIONS 定義に完全準拠。
 */

export const ROLE_PERMISSIONS: Record<string, readonly string[]> = {
  owner: [
    'contract.create',
    'contract.view',
    'contract.edit',
    'contract.approve',
    'contract.terminate',
    'notification.batch_execute',
    'general_request.create',
    'general_request.view',
    'general_request.edit',
    'general_request.approve',
    'purchase_request.create',
    'purchase_request.view',
    'purchase_request.edit',
    'purchase_request.approve',
    'purchase_request.terminate',
    'purchase_request.receive',
    'purchase_request.link_bill',
    'supplier.create',
    'supplier.view',
    'supplier.edit',
    'quotation.create',
    'quotation.view',
    'quotation.edit',
    'quotation.send',
    'quotation.convert',
    'deal.create',
    'deal.view',
    'deal.edit',
    'deal.close',
    'contract_renewal_link.create',
    'contract_renewal_link.view',
    'dashboard.view',
    'dashboard.executive_view',
    'recommendation.view',
    'recommendation.act',
  ],
  admin: [
    'contract.create',
    'contract.view',
    'contract.edit',
    'contract.approve',
    'contract.terminate',
    'notification.batch_execute',
    'general_request.create',
    'general_request.view',
    'general_request.edit',
    'general_request.approve',
    'purchase_request.create',
    'purchase_request.view',
    'purchase_request.edit',
    'purchase_request.approve',
    'purchase_request.terminate',
    'purchase_request.receive',
    'purchase_request.link_bill',
    'supplier.create',
    'supplier.view',
    'supplier.edit',
    'quotation.create',
    'quotation.view',
    'quotation.edit',
    'quotation.send',
    'quotation.convert',
    'deal.create',
    'deal.view',
    'deal.edit',
    'deal.close',
    'contract_renewal_link.create',
    'contract_renewal_link.view',
    'dashboard.view',
    'dashboard.executive_view',
    'recommendation.view',
    'recommendation.act',
  ],
  legal_admin: [
    'contract.create',
    'contract.view',
    'contract.edit',
    'contract.approve',
    'contract.terminate',
    'general_request.create',
    'general_request.view',
    'general_request.edit',
    'general_request.approve',
    'purchase_request.view',
    'purchase_request.approve',
    'supplier.view',
    'quotation.view',
    'deal.view',
    'contract_renewal_link.create',
    'contract_renewal_link.view',
    'dashboard.view',
    'dashboard.executive_view',
    'recommendation.view',
    'recommendation.act',
  ],
  legal_viewer: [
    'contract.view',
    'general_request.view',
    'purchase_request.view',
    'supplier.view',
    'quotation.view',
    'deal.view',
    'contract_renewal_link.view',
    'dashboard.view',
    'recommendation.view',
  ],
  approver: [
    'contract.view',
    'contract.approve',
    'general_request.view',
    'general_request.approve',
    'purchase_request.view',
    'purchase_request.approve',
    'purchase_request.receive',
    'supplier.view',
    'quotation.view',
    'deal.view',
    'contract_renewal_link.view',
    'dashboard.view',
    'dashboard.executive_view',
    'recommendation.view',
    'recommendation.act',
  ],
  accounting_manager: [
    'contract.view',
    'general_request.view',
    'purchase_request.view',
    'purchase_request.receive',
    'supplier.create',
    'supplier.view',
    'supplier.edit',
    'quotation.create',
    'quotation.view',
    'quotation.edit',
    'quotation.send',
    'quotation.convert',
    'deal.create',
    'deal.view',
    'deal.edit',
    'deal.close',
    'contract_renewal_link.create',
    'contract_renewal_link.view',
    'dashboard.view',
    'dashboard.executive_view',
    'recommendation.view',
    'recommendation.act',
  ],
  accountant: [
    'contract.view',
    'general_request.view',
    'purchase_request.view',
    'supplier.view',
    'dashboard.view',
    'dashboard.executive_view',
    'recommendation.view',
    'recommendation.act',
  ],
  payroll_admin: [
    'general_request.view',
    'dashboard.view',
    'dashboard.executive_view',
    'recommendation.view',
    'recommendation.act',
  ],
  sales_admin: [
    'quotation.create',
    'quotation.view',
    'quotation.edit',
    'quotation.send',
    'quotation.convert',
    'deal.create',
    'deal.view',
    'deal.edit',
    'deal.close',
    'contract_renewal_link.create',
    'contract_renewal_link.view',
    'dashboard.view',
    'dashboard.executive_view',
    'recommendation.view',
    'recommendation.act',
  ],
  sales_rep: [
    'quotation.create',
    'quotation.view',
    'quotation.edit',
    'quotation.send',
    'quotation.convert',
    'deal.create',
    'deal.view',
    'deal.edit',
    'deal.close',
    'contract_renewal_link.create',
    'contract_renewal_link.view',
    'dashboard.view',
    'recommendation.view',
    'recommendation.act',
  ],
  employee: [
    'contract.view',
    'general_request.create',
    'general_request.view',
    'purchase_request.create',
    'purchase_request.view',
    'quotation.view',
    'deal.view',
    'contract_renewal_link.view',
    'dashboard.view',
    'recommendation.view',
    'recommendation.act',
  ],
};

/**
 * ユーザーの保持ロールに基づき、指定の権限が存在するかチェックする
 */
export function hasPermission(roles: string[] | undefined | null, permission: string): boolean {
  if (!roles || roles.length === 0) return false;
  return roles.some((role) => {
    const perms = ROLE_PERMISSIONS[role];
    return perms ? perms.includes(permission) : false;
  });
}
